### ISSUE TITLE
[Alpha Testing] Title layout, introduce object, level number, enhancement

### ISSUE THREAD

**Issue by JiayiZheng** [LameLemon/CrimeHunter#154]
1. In title, set a better layout. Set all buttons in the middle of between header and "back to home" button.
2. In help, describe what does a hole image mean
3. Change level number, start from 1
4. For enhancement, connect all level road together, that is, after you pass one level, player car enter next level road automatically without showing the load page.

**Comment by darasy** [comment]
Hi,
1. We are still working on this as it is in the middle of some browser (i.e. Chrome, and Safari) and not for other browser (i.e. Firefox).
2, 3. we will take that into the consideration.
4. Since each level has a different layout, we think it is better to tell the player on which level they are in and how many enemies to kill, also refresh a new looking for different level appearance. We will consider about this though.

Thank you for your request! :)
CrimeHunter

**Comment by LameLemon** [comment]
The browser has been resolved during the Beta release, the pothole is explained in our help page. The structure of our game does not allow 'infinity' levels yet, because of this we will not be connecting multiple levels together. :)
